# Generated by Django 4.1.2 on 2022-11-07 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0003_aluno_foto_alter_aluno_id_alter_curso_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
